### ISSUE TITLE
Глава 1.3 - дописать про PoS

### ISSUE THREAD

**Issue by vlzhr** [KardanovIR/waves-book#1]
Под заголовком Fair PoS объяснение начинается с объяснения отличий нашего алгоритма от сырого PoS. Имхо, стоит добавить, что такое PoS вообще или хотя бы ссылку на то, где об этом почитать для newbies.

**Comment by KardanovIR** [comment]
Дописано, появилось в разделе про Network Features
https://github.com/KardanovIR/waves-book/blob/master/sections/2-Network-Features/2-2-mining-and-waves-ng.md
